language: ruby
rvm:
  - 2.4.1



before_install:
  openssl aes-256-cbc -K $encrypted_2288a4b9710c_key -iv $encrypted_2288a4b9710c_iv -in s3cfg-prod.enc -out s3cfg-prod -d
install: gem install jekyll jekyll-feed bootstrap-sass jekyll-archives jekyll-paginate-v2 bundler
script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
before_deploy: 
  - pip install --user s3cmd
  - pip install --user awscli
deploy:
    provider: script
    script: ~/.local/bin/s3cmd sync --config s3cfg-prod --reduced-redundancy --guess-mime-type --no-mime-magic --delete-removed --exclude '.sass-cache' --exclude 's3cfg*' _site/ s3://www.grange85.co.uk/swirling/
    skip_cleanup: true 
notifications:
    email:
        on_failure: always

after_deploy:
    aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/swirling/*"
