# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Everything's swirling
email: andy@grange85.co.uk
description: > # this means to ignore newlines until "baseurl:"
  It's what I am.
baseurl: "/swirling" # the subpath of your site, e.g. /blog
url: "http://www.grange85.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: grange85
github_username:  grange85
permalink: /:year/:month/:day/:title/
jekyll-archives:
  enabled: ['month','categories']
  layouts:
    month: month-archive
    category: category-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
paginate: 5


# Build settings
source: /media/xander4/DATA/13-SWIRLING/
destination: /home/andy/sites/www.grange85.co.uk/swirling/
version: 3.0.1
port: 4050
markdown: kramdown
exclude:  
  - Gemfile
  - Gemfile.lock
excerpt_separator: <!--more-->
